package vn.edu.fpt.SmartHealthC.exception;

import lombok.Data;
import org.springframework.http.HttpStatus;
import org.springframework.http.HttpStatusCode;

import lombok.Getter;

@Getter
public enum ErrorCode {
    //    UNCATEGORIZED_EXCEPTION(9999, "Uncategorized error", HttpStatus.INTERNAL_SERVER_ERROR),
//    INVALID_KEY(1001, "Uncategorized error", HttpStatus.BAD_REQUEST),
//    USER_EXISTED(1002, "User existed", HttpStatus.BAD_REQUEST),
//    UNAUTHENTICATED(1006, "Unauthenticated", HttpStatus.UNAUTHORIZED),
//    UNAUTHORIZED(1007, "You do not have permission", HttpStatus.FORBIDDEN),
    NOTIFICATION_SETTING_NOT_FOUND("Notification setting not found", HttpStatus.NOT_FOUND),
    FORBIDDEN("You do not have permission", HttpStatus.FORBIDDEN),
    APP_USER_NOT_FOUND_OR_NOT_ACTIVATED("AppUser not found or not activated", HttpStatus.NOT_FOUND),
    JWT_INVALID(",Invalid jwt token", HttpStatus.BAD_REQUEST),
    CREDENTIAL_EXPIRED("Your login session has expired", HttpStatus.UNAUTHORIZED),
    EMAIL_EXISTED("Email existed", HttpStatus.BAD_REQUEST),
    SEND_EMAIL_FAIL("Send email fail", HttpStatus.BAD_REQUEST),
    TOKEN_NOT_OWNED("Tokens are not owned ", HttpStatus.BAD_REQUEST),
    CODE_INVALID("Code invalid", HttpStatus.BAD_REQUEST),
    CODE_EXPIRED("Code expired", HttpStatus.BAD_REQUEST),
    EMAIL_NOT_EXISTED("Email not existed", HttpStatus.BAD_REQUEST),
    CREDENTIAL_INVALID("Wrong email or password", HttpStatus.BAD_REQUEST),
    REFRESH_TOKEN_NOT_EXIST("Refresh token not exist", HttpStatus.BAD_REQUEST),
    ACCESS_TOKEN_NOT_EXIST("Access token not exist", HttpStatus.BAD_REQUEST),
    REFRESH_TOKEN_EXPIRED("Refresh token expired", HttpStatus.BAD_REQUEST),
    UNAUTHENTICATED("Unauthenticated", HttpStatus.UNAUTHORIZED),
    UNAUTHORIZED("You do not have permission", HttpStatus.FORBIDDEN),
    APP_USER_NOT_FOUND("AppUser not found", HttpStatus.NOT_FOUND),
    USER_WEEK1_LESSON1_NOT_FOUND("User Week1 Lesson1 not found", HttpStatus.NOT_FOUND),
    USER_WEEK_START_NOT_EXIST("User not have record about week start", HttpStatus.NOT_FOUND),
    WEB_USER_NOT_FOUND("WebUser not found", HttpStatus.NOT_FOUND),
    WEB_USER_NOT_VALID("WebUser not valid", HttpStatus.BAD_REQUEST),
    BPS_NOT_FOUND("bps not found", HttpStatus.NOT_FOUND),
    NOT_FOUND("Not found", HttpStatus.NOT_FOUND),
    USER_NOT_EXISTED("User not existed", HttpStatus.NOT_FOUND),
    BLOOD_PRESSURE_NOT_FOUND("Blood pressure not found", HttpStatus.NOT_FOUND),
    DIET_RECORD_NOT_FOUND("Diet record not found", HttpStatus.NOT_FOUND),
    DIET_PLAN_EXIST("Diet plan exist", HttpStatus.BAD_REQUEST),
    STEP_PLAN_EXIST("Step plan exist", HttpStatus.BAD_REQUEST),
    ACTIVITY_RECORD_NOT_FOUND("Activity record not found", HttpStatus.NOT_FOUND),
    ACTIVITY_PLAN_NOT_FOUND("Activity record plan not found", HttpStatus.NOT_FOUND),
    DIET_PLAN_NOT_FOUND("Diet record plan not found", HttpStatus.NOT_FOUND),
    MEDICINE_PLAN_NOT_FOUND("Medicine record plan not found", HttpStatus.NOT_FOUND),
    MENTAL_PLAN_NOT_FOUND("Mental record plan not found", HttpStatus.NOT_FOUND),
    STEP_PLAN_NOT_FOUND("Step record plan not found", HttpStatus.NOT_FOUND),
    WEIGHT_PLAN_NOT_FOUND("Weight record plan not found", HttpStatus.NOT_FOUND),
    WEEK_REVIEW_EXIST("Week Review exist", HttpStatus.BAD_REQUEST),
    WEEK_REVIEW_NOT_EXIST("Week Review not exist", HttpStatus.BAD_REQUEST),

    ACTIVITY_DAY_DATA_EMPTY("Activity day not have data", HttpStatus.BAD_REQUEST),
    DIET_DAY_DATA_EMPTY("Diet day not have data", HttpStatus.BAD_REQUEST),
    MEDICINE_DAY_DATA_EMPTY("Medicine day not have data", HttpStatus.BAD_REQUEST),
    MENTAL_DAY_DATA_EMPTY("Mental day not have data", HttpStatus.BAD_REQUEST),
    STEP_DAY_DATA_EMPTY("Step day not have data", HttpStatus.BAD_REQUEST),
    DIET_DAY_NOT_FOUND("Diet record day not found", HttpStatus.NOT_FOUND),
    STEP_DAY_NOT_FOUND("Step record day not found", HttpStatus.NOT_FOUND),
    ACTIVITY_PLAN_EXIST("Activity Plan exist", HttpStatus.BAD_REQUEST),
    FORM_QUESTION_NOT_FOUND("Form question not found", HttpStatus.NOT_FOUND),
    FORM_QUESTION_NUMBER_DUPLICATE("Form question number duplicate", HttpStatus.NOT_FOUND),
    LESSON_NOT_FOUND("Lesson not found", HttpStatus.NOT_FOUND),
    USER_LESSON_NOT_FOUND("User lesson not found", HttpStatus.NOT_FOUND),
    MEDICINE_NOT_FOUND("Medicine not found", HttpStatus.NOT_FOUND),
    MEDICINE_DAY_NOT_FOUND("Medicine type day not found", HttpStatus.NOT_FOUND),
    MENTAL_RULE_IN_PLAN_NOT_FOUND("Mental rule in plan not found", HttpStatus.NOT_FOUND),
    SAT_SF_C_NOT_FOUND("SAT_SF_C not found", HttpStatus.NOT_FOUND),
    SAT_SF_I_NOT_FOUND("SAT_SF_I not found", HttpStatus.NOT_FOUND),
    SAT_SF_P_NOT_FOUND("SAT_SF_P not found", HttpStatus.NOT_FOUND),
    SF_NOT_FOUND("SF not found", HttpStatus.NOT_FOUND),
    STEP_RECORD_NOT_FOUND("Step record not found", HttpStatus.NOT_FOUND),
    QUESTION_NOT_FOUND("Question not found", HttpStatus.NOT_FOUND),
    CARDINAL_NOT_FOUND("Numeral not found", HttpStatus.NOT_FOUND),
    CARDINAL_DATA_DAY_EMPTY("Numeral data day empty", HttpStatus.NOT_FOUND),
    CARDINAL_TYPE_DAY_EXIST("Numeral type day exists", HttpStatus.BAD_REQUEST),
    BLOOD_PRESSURE_DAY_EXIST("Blood pressure day exists", HttpStatus.BAD_REQUEST),
    BLOOD_PRESSURE_DATA_DAY_EMPTY("Blood pressure day empty", HttpStatus.BAD_REQUEST),
    WEIGHT_DATA_DAY_EMPTY("Weight day empty", HttpStatus.BAD_REQUEST),
    MONTHLY_QUESTION_NOTFOUND("Monthly Question not found", HttpStatus.NOT_FOUND),
    RULE_FOR_PLAN_NOTFOUND("Rule For Plan not found", HttpStatus.NOT_FOUND),
    MENTAL_RULE_NOT_FOUND("Mental Rule not found", HttpStatus.NOT_FOUND),
    MENTAL_NOT_FOUND("Mental not found", HttpStatus.NOT_FOUND),
    MENTAL_PLAN_EXIST("Mental plan exist", HttpStatus.BAD_REQUEST),
    MEDICINE_TYPE_PLAN_NOT_FOUND("Medicine Type Plan not found", HttpStatus.NOT_FOUND),
    MEDICINE_TYPE_NOT_FOUND("Medicine type not found", HttpStatus.NOT_FOUND),
    MEDICINE_TYPE_EXIST("Medicine type exist", HttpStatus.BAD_REQUEST),
    MEDICINE_PLAN_EXIST("Medicine plan exist", HttpStatus.BAD_REQUEST),
    MEDICINE_TYPE_LIST_DUPLICATE("Medicine type list duplicate", HttpStatus.BAD_REQUEST),
    MEDICAL_APPOINTMENT_NOT_FOUND("Medical appointment not found", HttpStatus.NOT_FOUND),
    MEDICAL_HISTORY_NOT_FOUND("Medical history not found", HttpStatus.NOT_FOUND),
    USER_MEDICAL_HISTORY_NOT_FOUND("User medical history not found", HttpStatus.NOT_FOUND),
    WEIGHT_RECORD_NOT_FOUND("Weight record not found", HttpStatus.NOT_FOUND),
    WEIGHT_RECORD_DAY_EXIST("Weight record day  exists", HttpStatus.BAD_REQUEST),
    ACCOUNT_NOT_FOUND("Account not found", HttpStatus.NOT_FOUND),
    ACCOUNT_NOT_ACTIVATED("Account not activated", HttpStatus.NOT_ACCEPTABLE),
    NULL_ANSWER("Answer is null", HttpStatus.BAD_REQUEST),
    USER_CREATED("User created successfully", HttpStatus.CREATED),
    STAFF_CREATED("Staff created successfully", HttpStatus.CREATED),
    WRONG_OLD_PASSWORD("Wrong old password", HttpStatus.BAD_REQUEST),
    ACCOUNT_DELETED("Account has been deleted", HttpStatus.BAD_REQUEST),
    ACCOUNT_ACTIVATED("Account has been activated", HttpStatus.BAD_REQUEST),
    WEB_USER_FULL("Web user is full 10 patient", HttpStatus.BAD_REQUEST),
    ;

    ErrorCode(String message, HttpStatusCode statusCode) {
        this.message = message;
        this.statusCode = statusCode;
    }

    private final String message;
    private final HttpStatusCode statusCode;
}