CREATE TABLE `smarthealthc`.`user_week1_information` (
                                                       `Id` INT NOT NULL AUTO_INCREMENT,
                                                       `appuser_id` INT NOT NULL,
                                                       `intermediate_goal` VARCHAR(225) NULL,
                                                       `end_of_year_goal` VARCHAR(225) NULL,
                                                       `strength` VARCHAR(225) NULL,
                                                       `weak_point` VARCHAR(225) NULL,
                                                       `close_person1` VARCHAR(225) NULL,
                                                       `close_person2` VARCHAR(225) NULL,
                                                       `close_person1_message` VARCHAR(225) NULL,
                                                       `close_person2_message` VARCHAR(225) NULL,
                                                       `prefrerred_environment` VARCHAR(225) NULL,
                                                       `prefrerred_time` DATE NULL,
                                                       `not_preferred_location` VARCHAR(225) NULL,
                                                       `not_preferred_time` DATE NULL,
                                                       `score10` INT NULL,
                                                       `score20` INT NULL,
                                                       `score30` INT NULL,
                                                       `score40` INT NULL,
                                                       `score50` INT NULL,
                                                       `recent_values` VARCHAR(225) NULL,
                                                       `influence_onLife` VARCHAR(225) NULL,
                                                       `new_values` VARCHAR(225) NULL,
                                                       `reason_for_changing` VARCHAR(225) NULL,
                                                       `current_emotion` VARCHAR(225) NULL,
                                                       `why_if_realistic` VARCHAR(225) NULL,
                                                       `why_if_not_better_for_life` VARCHAR(225) NULL,
                                                       `no_more_than2` BIT(1) NULL,
                                                       `todo_list` BIT(1) NULL,
                                                       `no_procastinating` BIT(1) NULL,
                                                       `do_exercises` BIT(1) NULL,
                                                       `what_is_health` VARCHAR(225) NULL,
                                                       `activity_commitment` VARCHAR(225) NULL,
                                                       `diet_commitment` VARCHAR(225) NULL,
                                                       `mental_commitment` VARCHAR(225) NULL,
                                                       `medicine_commitment` VARCHAR(225) NULL,
                                                       `road_block` VARCHAR(225) NULL,
                                                       `solution` VARCHAR(225) NULL,
                                                       `commitment` VARCHAR(225) NULL,
                                                       PRIMARY KEY (`Id`),
                                                       INDEX `appuser_id_idx` (`appuser_id` ASC) VISIBLE,
                                                       CONSTRAINT `appuser`
                                                           FOREIGN KEY (`appuser_id`)
                                                               REFERENCES `smarthealthc`.`app_user` (`id`)
                                                               ON DELETE NO ACTION
                                                               ON UPDATE NO ACTION);

